name: "Setup job"
description: "Sets up node environment for a job"

runs:
  using: "composite"
  steps:
    - name: Recover modules cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.0'
        cache: 'yarn'

    - name: Cache Storybook
      id: cache-storybook
      uses: actions/cache@v2
      with:
        path: '**/custom-elements.json'
        key: storybook-${{ hashFiles('package-lock.json') }}
