name: "Setup job"
description: "Sets up node environment for a job"
inputs:
   node-version:
     required: false
     description: "The node version to use for this job"
     default: '16.20.0'

runs:
  using: "composite"
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
