#!/usr/bin/env sh

echo "\n--Pre-commit check--\n"

# Make nvm command available
[ -s "$NVM_DIR/nvm.sh" > /dev/null ] && . "$NVM_DIR/nvm.sh" > /dev/null
# Set correct node version
[ -f .nvmrc ] && nvm use > /dev/null

# Exit if any of the processes fail
set -e

# Pop stash if any of the processes fail
cleanup() {
  echo Exiting
  git stash pop || true

  exit $?
}
trap cleanup EXIT ERR

# Stash uncommited files
git stash --keep-index --include-untracked || true

# Validate and format code
npx tsc
npx yarn lint-fix
npx yarn format

# Stage and commit files that have been formatted
git add .

# Pop stash with uncommited files
git stash pop

echo "\n--Pre-commit check has passed--\n"
