#!/usr/bin/env sh

echo "\n--Pre-commit check--\n"

# Make nvm command available
[ -s "$NVM_DIR/nvm.sh" > /dev/null ] && . "$NVM_DIR/nvm.sh" > /dev/null
# Set correct node version
[ -f .nvmrc ] && nvm use > /dev/null

# Exit if any of the processes fail
set -e

# Pop stash if any of the processes fail
cleanup() {
  git stash pop || true
}
trap cleanup EXIT ERR

# Stash uncommited files
git stash --keep-index --include-untracked || true

# Validate and format code
npx yarn build || { echo "Error: build failed"; exit 1; }
npx yarn lint-fix || { echo "Error: lint failed"; exit 1; }
npx yarn format || { echo "Error: format failed"; exit 1; }

# Stage and commit files that have been formatted
git add .

echo "\n--Pre-commit check has passed--\n"
