name: Install and build
on: workflow_call
jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup job
        uses: ./.github/actions/setup-job

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      # Only cache node_modules for dependent jobs
      - name: Cache for dependent jobs
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: deps-${{ github.sha }}
          max-age: 14400 # 4 hours in seconds
