name: Install
on: workflow_call
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup job
        uses: ./.github/actions/setup-job

      - name: Install Dependencies
        run: yarn