name: Install
on: workflow_call
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup job
        uses: ./.github/actions/setup-job

      - name: Install Dependencies
        run: yarn

      # - name: Cache installation
      #   uses: actions/cache@v3
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

      # - name: Cache Cypress Binary
      #   id: cache-cypress-binary
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/Cypress
      #     key: binary-${{ hashFiles('package-lock.json') }}