name: Integration Test
on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ['atoms', 'molecules', 'organisms']
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup job
        uses: ./.github/actions/setup-job

      - name: Install Cypress
        run: yarn add cypress -W -D

      - name: Recover build cache
        uses: actions/cache@v3
        with:
          path: 'packages/components/**/lib'
          key: build-${{ github.sha }}

      - name: Build Storybook
        run: yarn build-storybook

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"