name: CI

on:
  push:
  pull_request:
    types: [closed]

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-job
      - name: Install Dependencies
        run: yarn

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-job
      - name: Build packages
        run: yarn build
      - name: Save build cache
        uses: actions/cache@v3
        with:
          path: 'packages/components/**/lib'
          key: build-${{ github.sha }}

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-job
      - name: Lint files
        run: yarn lint

  unit-test:
    needs: build
    strategy:
      matrix:
        folder: ["atoms", "molecules", "organisms"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-job
      - name: Run unit tests for ${{ matrix.folder }}
        run: yarn test packages/components/${{ matrix.folder }} --passWithNoTests

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["atoms", "molecules", "organisms"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-job
      - name: Recover build cache
        uses: actions/cache@v3
        with:
          path: 'packages/components/**/lib'
          key: build-${{ github.sha }}
      - name: Start storybook
        run: yarn storybook --ci &
      - name: Wait for Storybook to start
        run: npx wait-on http://localhost:6006 -t 120000
      - name: Run integration tests for ${{ matrix.folder }}
        run: yarn e2e --spec "packages/components/${{ matrix.folder }}/**/*.integration.spec.ts" || echo 'No tests found'

  publish:
    needs: [lint, unit-test, integration-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      packages: write
      actions: write
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-job
      - name: Set git config
        run: |
          git config --global user.email "jackblakeston93@gmail.com"
          git config --global user.name "Jack Blakeston"
      - name: Bump and Publish changed packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
            if lerna changed --json --loglevel=error | grep -qF "packages/"; then
              echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > ~/.npmrc
              yarn lerna version --yes --conventional-commits --no-changelog
              yarn lerna publish from-package --yes --no-verify-access --no-git-reset --no-git-tag-version --no-push
              rm -f ~/.npmrc
            else
              echo "No changes in packages"
            fi
