name: CI

on:
  push:
  pull_request:
    types: [closed]

jobs:
  install:
    uses: ./.github/workflows/install.yml

  build:
    needs: install
    uses: ./.github/workflows/build.yml

  lint:
    needs: build
    uses: ./.github/workflows/lint.yml

  unit-test:
    needs: build
    uses: ./.github/workflows/unit-test.yml

  integration-test:
    needs: build
    uses: ./.github/workflows/integration-test.yml

  publish:
    needs: [lint, unit-test, integration-test]
    uses: ./.github/workflows/publish.yml
