name: CI

on:
  push:
  pull_request:
    types: [closed]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn
      - name: Lint files
        run: yarn lint


  unit-test:
    needs: lint
    strategy:
      matrix:
        folder: ["atoms", "molecules", "organisms"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn
      - name: Run unit tests for ${{ matrix.folder }}
        run: yarn test packages/components/${{ matrix.folder }} --passWithNoTests

  integration-test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["atoms", "molecules", "organisms"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Start storybook
        run: yarn storybook &
      - name: Wait for Storybook to start
        run: npx wait-on http://localhost:6006 -T 120000
      - name: Run integration tests for ${{ matrix.folder }}
        run: yarn e2e --spec "packages/components/${{ matrix.folder }}/**/*" || echo 'No tests found'

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      packages: write
      actions: write
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn
      - name: Set up Git
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set git config
        run: |
          git config --global user.email "jackblakeston93@gmail.com"
          git config --global user.name "Jack Blakeston"
      - name: Bump and Publish changed packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
            if lerna changed --json --loglevel=error | grep -qF "packages/"; then
              echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > ~/.npmrc
              yarn lerna version --yes --conventional-commits --no-changelog
              yarn lerna publish from-package --yes --no-verify-access --no-git-reset --no-git-tag-version --no-push
            else
              echo "No changes in packages"
            fi