name: Branch push workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  install-and-build:
    uses: ./.github/workflows/install-and-build.yml

  deploy-storybook:
    needs: build
    uses: ./.github/workflows/deploy-storybook.yml
    secrets: inherit

  unit-test:
    needs: build
    uses: ./.github/workflows/unit-test.yml

  integration-test:
    needs: build
    uses: ./.github/workflows/integration-test.yml
