name: Merge to main workflow

on:
  push:
    branches:
      - main

jobs:
  install-and-build:
    uses: ./.github/workflows/install-and-build.yml

  deploy-storybook:
    needs: build
    uses: ./.github/workflows/deploy-storybook.yml
    secrets: inherit

  unit-test:
    needs: build
    uses: ./.github/workflows/unit-test.yml

  integration-test:
    needs: build
    uses: ./.github/workflows/integration-test.yml

  publish:
    needs: [unit-test, integration-test]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
