name: On push workflow
on: push
jobs:
  install-and-build:
    uses: ./.github/workflows/install-and-build.yml

  deploy-storybook:
    needs: install-and-build
    uses: ./.github/workflows/deploy-storybook.yml
    secrets: inherit

  unit-test:
    needs: install-and-build
    uses: ./.github/workflows/unit-test.yml

  integration-test:
    needs: install-and-build
    uses: ./.github/workflows/integration-test.yml

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [unit-test, integration-test]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
