name: Publish
on: workflow_call
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-job
      - name: Set git config
        run: |
          git config --global user.email "jackblakeston93@gmail.com"
          git config --global user.name "Jack Blakeston"
      - name: Bump and Publish changed packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn global add lerna@^6.5.1
          if lerna changed --json --loglevel=error | grep -qF "packages/"; then
            echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > ~/.npmrc
            yarn lerna version --yes --conventional-commits --no-changelog
            yarn lerna publish from-package --yes --no-verify-access --no-git-reset --no-git-tag-version --no-push
            rm -f ~/.npmrc
          else
            echo "No changes in packages"
          fi
