name: Publish
on: workflow_call
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup job
        uses: ./.github/actions/setup-job
      - name: Set git config
        run: |
          git config --global user.email "jackblakeston93@gmail.com"
          git config --global user.name "Jack Blakeston"
      - name: Bump and Publish changed packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          lerna -v
          echo $PATH
