name: Unit Test
on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["atoms", "molecules", "organisms"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup job
        uses: ./.github/actions/setup-job

      - name: Recover build cache
        uses: actions/cache@v3
        with:
          path: 'packages/components/**/lib'
          key: build-${{ github.sha }}

      - name: Run unit tests for ${{ matrix.folder }}
        run: yarn test packages/components/${{ matrix.folder }} --passWithNoTests
